### ISSUE TITLE
Moving docs into master

### ISSUE THREAD

**Issue by tgriesser** [swannodette/mori#104]
Wondering what you'd think about keeping the docs in master in a similar fashion as underscore, backbone, etc.

Benefits of this are the ability to actually see the docs locally without needing to flip between gh-pages and master branches, and the ability to update docs to reflect the state of master without needing to cut a new release, merging master into gh-pages at the time of cutting a new release would do the trick.

**Comment by glenjamin** [comment]
+1 from me on this. I have a bash script I can import that will rebuild gh-pages off current master which works pretty well

**Comment by swannodette** [comment]
PR welcome.
