### ISSUE TITLE
Expose arities for faster invokes

### ISSUE THREAD

**Issue by swannodette** [swannodette/mori#129]
We should expose direct access to the arities for blazing performance for writing critical sections. Just need to pick a standard convention. We could then write a macro that reflects through the ClojureScript compiler to emit the right code.

```js
var mut = mori.mutable,
    v   = mut.thaw(mori.vector());

mut.conj(0);
mut.conj.f1(0);
mut.conj.f2(0, 1);
mut.conj.fn(0, 2, 3, 4, 5);
```

**Comment by sgrove** [comment]
What about `mut.conj_f1`, `mut.conj_f2` to avoid the extra lookup? It's likely negligible, but I'm not sure there's a downside to it.

**Comment by swannodette** [comment]
There's really no need as this is the kind of thing modern JavaScript engines optimize.

**Comment by sgrove** [comment]
Just getting my bearing on cljs.analyzer here, but took a quick pass at it https://gist.github.com/sgrove/eb10a76284f71a01cd9b

I'm unclear on what the underlying js for `mori.conj.f1(0)` should look like. Currently it just wraps `mori.conj`, e.g.:

    goog.exportSymbol("mori.conj.f0",(function (){
    return mori.conj.call(null);
    }));
    
    goog.exportSymbol("mori.conj.f1",(function (coll){
    return mori.conj.call(null,coll);
    }));
    
    goog.exportSymbol("mori.conj.f2",(function (coll,x){
    return mori.conj.call(null,coll,x);
    }));
    
    goog.exportSymbol("mori.conj.fn",(function() { 
    var G__5554__delegate = function (xs){
    return cljs.core.apply.call(null,mori.conj,xs);
    };
    var G__5554 = function (var_args){
    var xs = null;
    if (arguments.length > 0) {
    var G__5555__i = 0, G__5555__a = new Array(arguments.length -  0);
    while (G__5555__i < G__5555__a.length) {G__5555__a[G__5555__i] = arguments[G__5555__i + 0]; ++G__5555__i;}
      xs = new cljs.core.IndexedSeq(G__5555__a,0);
    } 
    return G__5554__delegate.call(this,xs);};
    G__5554.cljs$lang$maxFixedArity = 0;
    G__5554.cljs$lang$applyTo = (function (arglist__5556){
    var xs = cljs.core.seq(arglist__5556);
    return G__5554__delegate(xs);
    });
    G__5554.cljs$core$IFn$_invoke$arity$variadic = G__5554__delegate;
    return G__5554;
    })()
    );

Which I doubt is helpful. Happy to rework it though.

**Comment by sgrove** [comment]
My first thought on this was to use a macro + cljs.analyzer to pull out the arities via metadata for a function, and then generate + expose individual functions for each arity, attaching them to the base exported function.

Invoking the macro  (in the `mori` ns in this case) `(gen-arities! mori.conj cljs.core/conj)` would generate

    goog.exportSymbol("mori.conj.f0",(function (){...}));
    goog.exportSymbol("mori.conj.f1",(function (coll){...}));
    goog.exportSymbol("mori.conj.f2",(function (coll,x){...}));
    goog.exportSymbol("mori.conj.fn",(function() {...}));

I might be misguided with this approach though - if you want to sketch out what we should reflect, and what we should emit, I can take care of it from there.

**Comment by swannodette** [comment]
@sgrove this looks fine to me! Note we still need to export the standard entry point.

**Comment by swannodette** [comment]
fixed https://github.com/swannodette/mori/commit/7a80330e1254feb06e295535a488852f5545576f
