### ISSUE TITLE
mori.equals does not benefit from structure sharing as it could

### ISSUE THREAD

**Issue by tomaskulich** [swannodette/mori#138]
> var m = require('mori'); // version 0.2.9
    > var hw = m.zipmap(
            m.map( function(i) {return "hello"+i},
                   m.range(1000000)),
            m.map( function(i) {return "world"+i},
                   m.range(1000000))
    );

    {“hello0” “world0”, “hello1” “world1”, ...}

    > var new_hw = m.assoc(hw, 'hello4747', 'just world');

    // this could be O(1), but it's not
    > m.equals(new_hw, hw) 
    false

    > new_hw = m.assoc(new_hw, 'hello4747', 'world4747')

    // once again, this could be O(1), but it's not
    > m.equals(new_hw, hw)
    true

**Comment by swannodette** [comment]
There's nothing to fix here. This is just how Clojure data structure equality works.

**Comment by tomaskulich** [comment]
well, right, this is not something that should be fixed in Mori project.
