### ISSUE TITLE
Browser goes into an infinite loop when printing a lazy sequence.

### ISSUE THREAD

**Issue by danielbraun** [swannodette/mori#164]
Ways to reproduce:
1. Go to Mori's website.
2. In the console, type: `mori.repeat(0).toString();`

I'm not sure how it can be solved. Crashing the browser as it does now is a problem.

**Comment by neverfox** [comment]
Infinite lazy sequences aren't toys, kiddos. Seriously though, this seems like expected behavior, despite resulting in a painful outcome.

**Comment by darwin** [comment]
I'm not a mori user, but in cljs you can limit number of levels and number of items printed. This effectively works around this problem when properly set.

Luckily for you, a quick glance over mori source revealed that those variables are somehow exported for you to use:
https://github.com/swannodette/mori/blob/master/src/mori/extra.cljs#L194-L197
