### ISSUE TITLE
Mori.js should not be minified

### ISSUE THREAD

**Issue by binarykitchen** [swannodette/mori#175]
It is not a good practice to already come with a minified version for npm packages.

This will slow down minification processes, i.E. gulp-uglify2 enormously.

Ultimately, it is up to the developer to minify code in the build process of the app using Mori.

That said, I recommend you to ship with an unminified `mori.js` and have another `mori.min.js`

**Comment by neverfox** [comment]
In the meantime, you should be able to use negation in `gulp.src` to exclude mori from minification.

**Comment by binarykitchen** [comment]
Yes, we could. Unfortunately our build process is having very long pipes, making it a bit too complicated.

All I am saying here is that npm packages should point to unminified code (from package.json, the main entry). And minified code can be either in a dist folder, a different name but ultimately it is up to the end user (developer) on how to minify, release and deploy it.

**Comment by binarykitchen** [comment]
@swannodette ?

**Comment by sesm** [comment]
Hi, @binarykitchen !
Unfortunately, generating non-minifed source for Mori would either add a lot of dead code to the bundle, or require a new compilation mode in Google Closure Compiler.
Let me explain why:  
Essentially, Mori is just a ClojureScript namespace, that imports some functions from ClojureScript core and export them under different names. The project is then compiled with Google Closure Compiler under Advanced compilation mode. This mode does several things:
1. Performs full-program optimization and dead code elimination. (As a result, you don't get the entire ClojureScript source in the budnle, but only a fraction of it, that is required to support exported functions and data structures) 
2. Minifies the source.
Currently Google Closure Compiler doesn't have a mode that does dead code elimination but doesn't minify the source (for the list of available modes, see https://developers.google.com/closure/compiler/docs/compilation_levels)
So we could either accept the current situation, or bear with a lot of dead code in Mori unminified source.
I've tried to build Mori under WHITESPACE_ONLY compilation mode, and then uglify the result. The resulting bundle size was ~900k.

**Comment by binarykitchen** [comment]
@sesm thank you for your good response. Since I am unfamiliar with cljs compilers, I have no idea but what you say makes sense given the inherent nature of how ClojureScript compilation and optimisations work.

We will have to fix this ourselves within our own project.
