### ISSUE TITLE
Is mori.js dead ?

### ISSUE THREAD

**Issue by etienne-dldc** [swannodette/mori#200]
## This library looks dead...

Does someone know any active fork or alternative ?

**Comment by SeanSanker** [comment]
yes

**Comment by SeanSanker** [comment]
Alternative: https://facebook.github.io/immutable-js/

I guess

**Comment by etienne-dldc** [comment]
Other alternative : https://github.com/frptools/collectable

**Comment by kellenlask** [comment]
Immutable JS has gross naming/wrong perspective, and Ramda isn't immutable. Mori please?

**Comment by jligeza** [comment]
Is mori dead, or just everything has been done, and there is no need for more features? I'm only worried that the data structures might have been improved (performance wise) in clojure script, and these are not present in mori.

**Comment by hallettj** [comment]
I use Mori for my own projects despite the lack of updates. I offered to take over maintenance at one point, but I did not get a response from the author.

I've stuck with Mori because most operations produce lazily-evaluated sequences, and IMO the API is more amenable to type-checking with Flow compared to Immutable.js.

**Comment by jligeza** [comment]
@hallettj You could fork the repo, advertise it here, and update it. If the author ever wakes up, then he could merge it. I would use the fork in my new project.

**Comment by mwiencek** [comment]
@hallettj Especially if you're maintaining Flow types for Mori that work with a recent version of Flow; I think that would be very useful to people (me :)). I saw that the older definitions were [removed from flow-typed recently](https://github.com/flowtype/flow-typed/commit/da30fe6876482fc3782105f280150e71151ad92b), which made me sad, but I couldn't get those to work with Flow 0.6x anyway ([related](https://github.com/facebook/flow/issues/4492#issuecomment-320745178)).

**Comment by hallettj** [comment]
@mwiencek Oh I did not realize the definitions were removed from flow-typed! I would like to get them back in there at least. In the meantime there is a copy of the definitions that I use here: https://github.com/PoodleApp/poodle/blob/master/packages/arfe/types/mori.js

**Comment by Ebuall** [comment]
Is this still used in clojurescript itself?

**Comment by airportyh** [comment]
@Ebuall based on my investigation, it appears that the original source is in ClojureScript core, and mori.js is the result of compile that code into JavaScript. So, I would say the answer is yes.

**Comment by rosejn** [comment]
Mori basically is Clojurescript that has been exposed to JS, so it is rock solid.  There have been some updates in the intervening years, but nothing major.  If you wanted to get the latest changes it would likely be as simple as updating the version numbers in the project.clj to the latest versions and then recompiling to javascript.

https://github.com/swannodette/mori/blob/master/project.clj#L5

**Comment by brancusi** [comment]
This is great news. Has anyone done this? Any issues in getting the upgrade? Have there been enough updates to justify upgrading here?
