### ISSUE TITLE
Node REPL experience

### ISSUE THREAD

**Issue by pd** [swannodette/mori#24]
I just spent the morning integrating mori into a project I'm working on, which has let me delete a lot of one-off data structures I had lying around. Next up, maybe port it to ClojureScript, which looks pretty appealing right now. =)

Meanwhile, it'd be nice to see a useful `inspect` on `vector`/`hash_map`/etc, so that working in the REPL is less tiresome. I tried to investigate doing this myself, but without prior ClojureScript experience, it was unclear how to approach it.

Take a hashmap as an example:

```js
> h = m.hash_map(1, {some: 'object'}, 2, {another: 'object'})
{ k: null,
  j: 2,
  root: { w: {}, z: 6, g: [ 1, [Object], 2, [Object], , , ,  ] },
  Q: false,
  U: null,
  o: null,
  t: 4,
  n: 16123663 }
```

Daunting.

With a minimal `inspect` function attached, we could have:

```js
> h.inspect = function(d) { return this.toString(); }
[Function]
> h
{1 #<[object Object]>, 2 #<[object Object]>}
```

And in node 0.11.2 (devel release), thanks to joyent/node@66280de, we could even have:

```js
> h.inspect = function(d) { return m.clj_to_js(this); }
[Function]
> h
{ '1': { some: 'object' }, '2': { another: 'object' } }
```

If this seems reasonable (well, the 0.10.x version, for now), and you could give me a hint where to implement this, I'd be happy to try my hand at it.

**Comment by swannodette** [comment]
printing has already been fixed, printing of JS objects can be for another ticket.
