### ISSUE TITLE
js_to_clj doesn't work in the CoffeeScript REPL

### ISSUE THREAD

**Issue by grncdr** [swannodette/mori#37]
![I feel like I'm taking crazy pills](http://i.qkme.me/3s1j1g.jpg)

... but this appears to be true. I'm completely stymied as to how this behaviour is even possible, and it's obviously difficult to write a test case for it, but here's my shell session so others can attempt to reproduce it:

```
$ git log -1 --oneline
0f825ab js highlighting
$ node -v
v0.10.4
$ node
> var mori = require('mori')
undefined
> mori.js_to_clj([1, 2, 3])
[1 2 3]
> mori.js_to_clj({x: 1})
{"x" 1}
>
```

So far so good, we call `js_to_clj`, we get nice vectors and maps back, lets try CoffeeScript:

```
$ coffee -v
CoffeeScript version 1.6.3
$ coffee
coffee> mori = require './'
{ count: [Function: O],
  empty: [Function],
... and so on and so forth ...
coffee> mori.js_to_clj([1, 2, 3])
[ 1, 2, 3 ]
coffee> mori.js_to_clj({x: 1})
{ x: 1 }
coffee> mori.js_to_clj({x: 1}).constructor
[Function: Object]
```

So, that's pretty weird right? maybe some bug in the CS compiler (somehow...) but here's where my brain melts:

```
$ cat coffee-test.coffee
mori = require './'
myvec = console.log(mori.js_to_clj([1, 2, 3]))
console.log(myvec.constructor)
mymap = console.log(mori.js_to_clj({x: 1}))
console.log(mymap.constructor)
$ coffee coffee-test.coffee
[1 2 3]
[Function: Yg]
{"x" 1}
[Function: Eh]
```

Any ideas?

**Comment by swannodette** [comment]
Not going to look into this one.
