### ISSUE TITLE
Define shorthand for mori.curry(mori.get, "key")

### ISSUE THREAD

**Issue by glenjamin** [swannodette/mori#94]
I've found myself writing things like this quite a lot:

``` js
m = require('mori');
var getName = m.curry(m.get, "name")

var names = m.map(getName, collection_of_hash_maps);
```

In real clojure, we'd use keywords for this case, but that's trickier in mori - is this something other people are running into as well?

I'm not sure what a good name for this would be, some suggestions are below

``` js
m.key("name")
m.get_key("name")
m.partial_key("name")
m.curry_get("name")
m.getter("name")
```

**Comment by ashnur** [comment]
I don't see how that function would work. `xs` is just `"name0"`, the rest of the arguments are not even used.

And I also have this question, that I would like to partially apply the key I am looking for to `get`, but the ordering of the arguments is just wrong.
